package management

import (
	"context"
	"errors"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var scaffoldIdentifier = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)

type Scaffolder struct {
	FrameworkVersion string
	// FrameworkReplace is intended for framework development and tests. Normal
	// generated projects pin FrameworkVersion without a replace directive.
	FrameworkReplace string
}

func (scaffolder Scaffolder) StartProject(ctx context.Context, parent, name string) (root string, resultErr error) {
	if !scaffoldIdentifier.MatchString(name) {
		return "", fmt.Errorf("godjango startproject: invalid project name %q", name)
	}
	if scaffolder.FrameworkVersion == "" ||
		scaffolder.FrameworkVersion == "(devel)" ||
		scaffolder.FrameworkVersion == "latest" {
		return "", errors.New("godjango startproject: a pinned framework version is required")
	}
	parent, err := filepath.Abs(parent)
	if err != nil {
		return "", err
	}
	root = filepath.Join(parent, name)
	if err := os.Mkdir(root, 0o755); err != nil {
		if errors.Is(err, os.ErrExist) {
			return "", fmt.Errorf("godjango startproject: refusing to overwrite %s", root)
		}
		return "", err
	}
	defer func() {
		if resultErr != nil {
			resultErr = errors.Join(resultErr, os.RemoveAll(root))
		}
	}()

	for _, directory := range []string{
		"cmd/manage",
		"cmd/server",
		"internal/project",
		"apps",
	} {
		if err := os.MkdirAll(filepath.Join(root, filepath.FromSlash(directory)), 0o755); err != nil {
			return "", err
		}
	}

	goMod := fmt.Sprintf(
		"module %s\n\ngo 1.26.5\n\nrequire github.com/bon5co/godjango %s\n",
		name,
		scaffolder.FrameworkVersion,
	)
	if scaffolder.FrameworkReplace != "" {
		replacement, err := filepath.Abs(scaffolder.FrameworkReplace)
		if err != nil {
			return "", err
		}
		goMod += "\nreplace github.com/bon5co/godjango => " + filepath.ToSlash(replacement) + "\n"
	}
	files := map[string]string{
		ProjectMarker: fmt.Sprintf(
			"module=%s\nframework=github.com/bon5co/godjango@%s\n",
			name,
			scaffolder.FrameworkVersion,
		),
		"go.mod": goMod,
		"cmd/manage/main.go": fmt.Sprintf(`package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"github.com/bon5co/godjango/management"
	configuredproject "%s/internal/project"
)

func main() {
	configured, err := configuredproject.Configure()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(management.ExitFailure)
	}
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	os.Exit(management.ExecuteProject(
		ctx,
		os.Args[1:],
		management.ProjectOptions{Project: configured},
		management.Streams{In: os.Stdin, Out: os.Stdout, Err: os.Stderr},
	))
}
`, name),
		"cmd/server/main.go": `package main

import "fmt"

func main() {
	fmt.Println("GoDjangGo server wiring is generated by the HTTP runtime slice")
}
`,
		"internal/project/settings.go": fmt.Sprintf(`package project

import gdproject "github.com/bon5co/godjango/project"

type Settings struct{}

func (Settings) Validate() error { return nil }

func Configure() (*gdproject.Project, error) {
	return gdproject.New(Settings{}, Apps()...)
}
`),
	}
	for name, content := range files {
		if strings.HasSuffix(name, ".go") {
			formatted, err := format.Source([]byte(content))
			if err != nil {
				return "", fmt.Errorf("format generated %s: %w", name, err)
			}
			content = string(formatted)
		}
		if err := writeNew(filepath.Join(root, filepath.FromSlash(name)), content); err != nil {
			return "", err
		}
	}
	if err := writeAppRegistry(root, name, nil); err != nil {
		return "", err
	}
	if err := runGoModTidy(ctx, root); err != nil {
		return "", err
	}
	return root, nil
}

func (scaffolder Scaffolder) StartApp(root, name string) error {
	if !scaffoldIdentifier.MatchString(name) {
		return fmt.Errorf("godjango startapp: invalid app name %q", name)
	}
	projectRoot, err := DiscoverProject(root)
	if err != nil {
		return err
	}
	module, err := moduleName(projectRoot)
	if err != nil {
		return err
	}
	appRoot := filepath.Join(projectRoot, "apps", name)
	if err := os.Mkdir(appRoot, 0o755); err != nil {
		if errors.Is(err, os.ErrExist) {
			return fmt.Errorf("godjango startapp: app %q already exists", name)
		}
		return err
	}
	cleanup := true
	defer func() {
		if cleanup {
			_ = os.RemoveAll(appRoot)
		}
	}()

	for _, directory := range []string{"migrations", "templates"} {
		if err := os.Mkdir(filepath.Join(appRoot, directory), 0o755); err != nil {
			return err
		}
	}
	appSource := fmt.Sprintf(`package %s

type App struct{}

func New() *App { return &App{} }

func (*App) Name() string { return %q }
`, name, name)
	files := map[string]string{
		"app.go":      appSource,
		"models.go":   "package " + name + "\n",
		"routes.go":   "package " + name + "\n",
		"commands.go": "package " + name + "\n",
	}
	for fileName, content := range files {
		formatted, formatErr := format.Source([]byte(content))
		if formatErr != nil {
			return formatErr
		}
		if err := writeNew(filepath.Join(appRoot, fileName), string(formatted)); err != nil {
			return err
		}
	}

	apps, err := appDirectories(projectRoot)
	if err != nil {
		return err
	}
	if err := writeAppRegistry(projectRoot, module, apps); err != nil {
		return err
	}
	cleanup = false
	return nil
}

func writeAppRegistry(root, module string, apps []string) error {
	sort.Strings(apps)
	var imports strings.Builder
	var values strings.Builder
	for _, app := range apps {
		_, _ = fmt.Fprintf(&imports, "\t%q\n", module+"/apps/"+app)
		_, _ = fmt.Fprintf(&values, "\t\t%s.New(),\n", app)
	}
	source := fmt.Sprintf(`package project

import (
	gdproject "github.com/bon5co/godjango/project"
%s)

func Apps() []gdproject.App {
	return []gdproject.App{
%s	}
}
`, imports.String(), values.String())
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return err
	}
	path := filepath.Join(root, "internal", "project", "apps.go")
	return os.WriteFile(path, formatted, 0o644)
}

func appDirectories(root string) ([]string, error) {
	entries, err := os.ReadDir(filepath.Join(root, "apps"))
	if err != nil {
		return nil, err
	}
	var apps []string
	for _, entry := range entries {
		if entry.IsDir() && scaffoldIdentifier.MatchString(entry.Name()) {
			if _, err := os.Stat(filepath.Join(root, "apps", entry.Name(), "app.go")); err == nil {
				apps = append(apps, entry.Name())
			}
		}
	}
	sort.Strings(apps)
	return apps, nil
}

func moduleName(root string) (string, error) {
	content, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return "", err
	}
	for _, line := range strings.Split(string(content), "\n") {
		fields := strings.Fields(line)
		if len(fields) == 2 && fields[0] == "module" {
			return fields[1], nil
		}
	}
	return "", errors.New("godjango: project go.mod has no module declaration")
}

func runGoModTidy(ctx context.Context, root string) error {
	command := exec.CommandContext(ctx, "go", "mod", "tidy")
	command.Dir = root
	command.Env = os.Environ()
	output, err := command.CombinedOutput()
	if err != nil {
		return fmt.Errorf("godjango startproject: go mod tidy: %w\n%s", err, output)
	}
	return nil
}

func writeNew(path, content string) error {
	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		return err
	}
	if _, err := file.WriteString(content); err != nil {
		_ = file.Close()
		return err
	}
	return file.Close()
}
